In [2]:
import numpy as np 


In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [5]:
np.array(a)

array([1, 2, 3, 4, 5])

In [6]:
arr = [[1,2,3],[4,5,6],[7,8,9]]
np.array(arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr=np.arange(1,11,2)

In [8]:
arr = np.zeros((6,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [ ]:
# random generation function 

np.random.rand(10)

# this is a radom vector this is not a matrix 



array([0.37446074, 0.52172834, 0.84935128, 0.42556842, 0.41616914,
       0.45565477, 0.48849908, 0.73467132, 0.89238789, 0.42669998])

In [ ]:
np.random.randn(10)

# in this number comes betweenn -3 to 3

array([-0.32974624,  0.27106719,  0.04613017, -0.40907639, -1.0237846 ,
       -1.21419249, -1.09512019, -0.24398279,  0.4415747 ,  0.21852828])

In [24]:
np.random.randint(6)

# this function generate any random number between 0 to 6

3

In [ ]:
np.random.randint(10,20,10)

# in this we gave low ,high,size and then they print random number between low and high on the basis of size 


array([12, 19, 16, 15, 17, 10, 14, 12, 13, 18], dtype=int32)

array attributes


In [26]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr.shape

(3, 3)

In [28]:
arr.size

9

In [29]:
arr.dtype

dtype('int64')

array methods


In [30]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr.min()

np.int64(1)

In [32]:
arr.max()

np.int64(9)

In [33]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis=0)

# this is use to find sum of each coloumn

array([12, 15, 18])

In [ ]:
np.sum(arr,axis=1)

# this is use to find sum of each row

array([ 6, 15, 24])

In [37]:
arr.mean()


np.float64(5.0)

In [38]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax()
# finding index of tthe max elem

np.int64(8)

In [ ]:
arr.argmin()
# finding index of the min element 

np.int64(0)

reshaping and resizing 

In [41]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr =arr.reshape(5,6)

# for reshaping the array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])