In [1]:
import numpy as np 


In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [4]:
np.array(a)

array([1, 2, 3, 4, 5])

In [11]:
arr = [[1,2,3],[4,5,6],[7,8,9]]
np.array(arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr=np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [21]:
arr = np.zeros((6,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [26]:
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])