In [1]:
import numpy as np

In [2]:
s = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]

])

In [3]:
s.sum()

np.int64(405)

In [4]:
b = np.sum(s,axis = 1)   # sum of all rows 

In [5]:
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [6]:
for i in b:
    print(i)

45
45
45
45
45
45
45
45
45


In [9]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [10]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [19]:
for i in range(0,9,3):
    for j in range(0,9,3):
        # print(s[i:i+3,j:j+3])

        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45
