In [17]:
import numpy as np 


In [18]:
python_list = [[1,2,3,8],[4,5,6,7]]


In [19]:
arr = np.array(python_list)
arr

array([[1, 2, 3, 8],
       [4, 5, 6, 7]])

In [20]:
bool_arr =np.array([0 , 1, -1, 0, 0] ,dtype=bool)
print(bool_arr)

[False  True  True False False]


coverting numpy array to list 

In [ ]:
# # We can always convert an array back to a python list using tolist().

array = np.array([[1, 2, 3, 8],
                  [4, 5, 6, 7]])

nplist = array.tolist()
print(nplist)


[[1, 2, 3, 8], [4, 5, 6, 7]]


In [ ]:
# creating nummpy array to tuple 
python_tuple = (1,2,3,4,5)
print(type(python_tuple))

ntuple = np.array(python_tuple)
print(ntuple)

<class 'tuple'>
[1 2 3 4 5]


In [39]:

nums = np.array([1,2,3,4,5])
print(nums)
print("shape of nums:" , nums.shape)

numpy_two_dimensional_list = np.array([[0,1,2,4,5,6],
                                       [3,4,5,6,7,8],
                                       [6,7,8,9,10,11]])
print('shape of two dimention : ' , numpy_two_dimensional_list.shape)

print("reshape of two dimention:", numpy_two_dimensional_list.reshape(6,3))


[1 2 3 4 5]
shape of nums: (5,)
shape of two dimention :  (3, 6)
reshape of two dimention: [[ 0  1  2]
 [ 4  5  6]
 [ 3  4  5]
 [ 6  7  8]
 [ 6  7  8]
 [ 9 10 11]]


In [41]:
# data type of numpy array 

int_lists = [-3,-2,-1,0,1,2,3]
int_array = np.array(int_lists)
float_arr = np.array(int_lists,dtype = float)

print(int_array)
print(int_array.dtype)
print(float_arr)
print(float_arr.dtype)


[-3 -2 -1  0  1  2  3]
int64
[-3. -2. -1.  0.  1.  2.  3.]
float64
