In [3]:
import numpy as np

numpy indexing and slicing of vectors 

In [4]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[6]

np.int64(17)

In [6]:
arr[8]

np.int64(19)

In [ ]:
arr[2:6:2]
# slicing [start:end:step]

array([13, 15])

In [12]:
arr[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

matrix indexing

In [13]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [16]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [17]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [18]:
arr[3,2]

np.int64(18)

In [22]:
arr[0:2,1:3]

# first row 0 row to 1 row the column 1st row to 2nd row 

array([[2, 3],
       [7, 8]])

In [ ]:
arr[:,2]
# printing column

array([ 3,  8, 13, 18, 23, 28])

boolean indexing 

In [24]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [30]:
bool_index = arr%2==0
bool_index

array([ True,  True,  True,  True,  True])

In [31]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])