In [95]:
import numpy as np

arithmetic operations

In [96]:
a1 = np.array([1,2,3,4,5])
a2= np.array([6,7,8,9,10])
a1

array([1, 2, 3, 4, 5])

In [97]:
a1+ a2

array([ 7,  9, 11, 13, 15])

In [98]:
a2 - a1

array([5, 5, 5, 5, 5])

In [99]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [100]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [101]:
a1 // a2

array([0, 0, 0, 0, 0])

In [102]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

broadcasting
<!-- means when we add sub in matrix or array -->

In [103]:
l = [10,20,30,40,50]
arr = np.array(l)
arr

array([10, 20, 30, 40, 50])

In [104]:
arr +=10
arr

array([20, 30, 40, 50, 60])

In [105]:
arr *=20
arr

array([ 400,  600,  800, 1000, 1200])

In [106]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [107]:
arr2 + 10
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

deep and shallow copy

In [108]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [109]:
slice =a[:5]
slice *= 10
slice

array([10, 20, 30, 40, 50])

In [110]:
a
# whenever u r slicing an array wo apni alg position or space alocate karlete hai thats why jo main array hota hai usmae koi changes nhi hote like lists 

# this is the concept of shallow copy 

array([10, 20, 30, 40, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [111]:
slice2 =a[4:7]
slice2 +=20
slice2

array([70, 26, 27])

In [112]:
# whenever we make changes in array through slicing the main array also changed 

# this is the concept of deep copy 

a 
b = a


In [113]:
b [0] =99


In [114]:
b

array([99, 20, 30, 40, 70, 26, 27,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [115]:
a

array([99, 20, 30, 40, 70, 26, 27,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

<!-- if u r slicing any portion in array in that case that slice takes another position or location to store that elem    -->  concept of shallow 

<!-- but if u r copy the whole a aaray into b then  where array a is storing now array b is also storing at that same place so when u make changes on one array that the same changes happened in another array too --> concept of deep 

In [116]:
a
b = a.copy()

In [117]:
b[0] = 29

In [118]:
b

array([29, 20, 30, 40, 70, 26, 27,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [119]:
a

array([99, 20, 30, 40, 70, 26, 27,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

matrix operations

In [120]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])


In [121]:
A

array([[1, 2],
       [3, 4]])

In [122]:
B

array([[5, 6],
       [7, 8]])

In [123]:
A @ B  #for multiplication in matrix 

array([[19, 22],
       [43, 50]])

In [124]:
np.dot(A,B)  #for multiplication in matrix 

array([[19, 22],
       [43, 50]])

In [125]:
A

array([[1, 2],
       [3, 4]])

In [126]:
# transpose basically col become row and row become col
A.T


array([[1, 3],
       [2, 4]])

advance array manipulation 

stacking array 
<!-- YOU CAN NOT STACKED TWO MATRIX ARRAY  -->
<!-- YOU CAN STACKED TWO VECOTOR OR LINERA ARRAY -->


In [127]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [128]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [129]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [130]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

splitting array

In [131]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [133]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [136]:
a =np.vsplit(c,2)

In [137]:
for i in a:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
