In [1]:
import numpy as np

arithmetic operations

In [2]:
a1 = np.array([1,2,3,4,5])
a2= np.array([6,7,8,9,10])
a1

array([1, 2, 3, 4, 5])

In [3]:
a1+ a2

array([ 7,  9, 11, 13, 15])

In [5]:
a2 - a1

array([5, 5, 5, 5, 5])

In [6]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [8]:
a1 // a2

array([0, 0, 0, 0, 0])

In [9]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

broadcasting
<!-- means when we add sub in matrix or array -->

In [11]:
l = [10,20,30,40,50]
arr = np.array(l)
arr

array([10, 20, 30, 40, 50])

In [12]:
arr +=10
arr

array([20, 30, 40, 50, 60])

In [13]:
arr *=20
arr

array([ 400,  600,  800, 1000, 1200])

In [21]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arr2 + 10
arr2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

deep and shallow copy

In [22]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
slice =a[:5]
slice *= 10
slice

array([10, 20, 30, 40, 50])

In [ ]:
a
# whenever u r slicing an array wo apni alg position or space alocate karlete hai thats why jo main array hota hai usmae koi changes nhi hote like lists 

# this is the concept of shallow copy 

array([10, 20, 30, 40, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
slice2 =a[4:7]
slice2 +=20
slice2

array([70, 26, 27])

In [28]:
# whenever we make changes in array through slicing the main array also changed 

# this is the concept of deep copy 

a 
b = a


In [29]:
b [0] =99


In [30]:
b

array([99, 20, 30, 40, 70, 26, 27,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
a

array([99, 20, 30, 40, 70, 26, 27,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

<!-- if u r slicing any portion in array in that case that slice takes another position or location to store that elem    -->  concept of shallow 

<!-- but if u r copy the whole a aaray into b then  where array a is storing now array b is also storing at that same place so when u make changes on one array that the same changes happened in another array too --> concept of deep 

In [32]:
a
b = a.copy()

In [33]:
b[0] = 29

In [34]:
b

array([29, 20, 30, 40, 70, 26, 27,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
a

array([99, 20, 30, 40, 70, 26, 27,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

matrix operations

In [36]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])


In [37]:
A

array([[1, 2],
       [3, 4]])

In [38]:
B

array([[5, 6],
       [7, 8]])

In [39]:
A @ B

array([[19, 22],
       [43, 50]])