In [3]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [6]:
a = [1,2,3,4,5,"hellooo"]
a

[1, 2, 3, 4, 5, 'hellooo']

In [7]:
np.array(a)

array(['1', '2', '3', '4', '5', 'hellooo'], dtype='<U21')

In [8]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr =np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [7]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [6]:
# rows and coloumns
arr= np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [3]:
arr = np.ones((4,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [11]:
np.random.rand(5)

array([0.67038504, 0.67319591, 0.48101012, 0.44991497, 0.95631768])

In [12]:
np.random.randn(10)

array([ 0.2800702 ,  1.37302093,  1.34951802, -1.17963022,  0.351533  ,
        0.32348408,  0.47390311,  0.25254482,  1.51216024,  0.65129908])

In [13]:
np.random.randint(10,20,10)

array([19, 19, 17, 13, 15, 18, 16, 18, 16, 12], dtype=int32)

In [14]:
arr=np.array([ [3,4,5],[2,3,4],[9,8,6] ])
arr

array([[3, 4, 5],
       [2, 3, 4],
       [9, 8, 6]])

Array Attributes

In [15]:
arr = np.array([[1,2,3],[3,4,5],[6,7,8]])
arr

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
arr.shape

(3, 3)

In [17]:
arr.size

9

In [18]:
arr.dtype

dtype('int64')

Array Methods

In [19]:
arr

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
arr.max()

np.int64(8)

In [22]:
arr.min()

np.int64(1)

In [23]:
arr.sum()

np.int64(39)

In [ ]:
# for column
np.sum(arr,axis = 0)

# for row

# np.sum(arr,axis = 1)

array([ 6, 12, 21])

In [30]:
arr.mean()

np.float64(4.333333333333333)

In [31]:
arr.std()

np.float64(2.211083193570267)

In [32]:
# for finding max value's index
arr.argmax()

np.int64(8)

In [33]:
# for finding min value's index
arr.argmin()

np.int64(0)

Reshaping and resizing

In [35]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [36]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])