In [7]:
import numpy as np

ARRAY OPERATION 

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

b

# in this both arr size should be same 

array([ 6,  7,  8,  9, 10])

In [ ]:
a1 =a+b

array([ 7,  9, 11, 13, 15])

In [15]:
a - b

array([-5, -5, -5, -5, -5])

In [16]:
a / b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [17]:
a//b

array([0, 0, 0, 0, 0])

In [19]:
l =[10,20,30,40,40]
arr=np.array(l)

In [20]:
arr+10

array([20, 30, 40, 50, 50])

In [21]:
arr2 =np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
a=arr2+10

DEEP AND SHALLOW COPY

In [25]:
a =np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice=a[:5]
slice+=10
slice

# this is the shallow copy in this there will be a no change after slicing or doing any operation on array 

array([11, 12, 13, 14, 15])

In [27]:
a

array([11, 12, 13, 14, 15,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
a[4:8]*10

array([150,  60,  70,  80])

In [ ]:
a


array([110, 120, 130, 140, 150,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200])

In [31]:
a
b=a

In [32]:
b

array([11, 12, 13, 14, 15,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
b[0]=99
b
# this is deep copy in this changes will be visible on the original array

array([99, 12, 13, 14, 15,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
a

array([99, 12, 13, 14, 15,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a=b.copy()
# this is shallow copy 

array([99, 12, 13, 14, 15,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
b[0]=76
b

array([76, 12, 13, 14, 15,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
a

array([99, 12, 13, 14, 15,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

MATRIX OPERATION

In [46]:
a= np.array([[2,4],[5,7]])
b= np.array([[6,7],[3,8]])

In [47]:
a

array([[2, 4],
       [5, 7]])

In [48]:
b

array([[6, 7],
       [3, 8]])

In [ ]:
a @ b
# multiplication 

array([[24, 46],
       [51, 91]])

In [ ]:
np.dot(a,b)
# multiplication

array([[24, 46],
       [51, 91]])

In [51]:
a

array([[2, 4],
       [5, 7]])

In [ ]:
a.T
# transpose = row become column and column become row 

array([[2, 5],
       [4, 7]])

ADVANNCE ARRAY MANIPULATION

STACKING ARRAY

In [53]:
a

array([[2, 4],
       [5, 7]])

In [54]:
b

array([[6, 7],
       [3, 8]])

In [56]:
a = np.array([1,2,3,4])
b= np.array([6,7,8,9])
# we can not stack two matrics 

In [ ]:
np.vstack((a,b))
# vertical stack

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [ ]:
np.hstack((a,b))
# horizontal stack = adding both array
# it become 1d array

array([1, 2, 3, 4, 6, 7, 8, 9])

In [ ]:
np.column_stack((a,b))

# in stacking u can only use vectors u can not use matrics 

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [61]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c,2)
# this operation split array into horizontal 

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.vsplit(c,2)
# this operation split array in veertial way

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]