In [2]:
import numpy as np

In [3]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [4]:
b = np.sum(s,axis =1)
b==45


array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [5]:
b = np.sum(s,axis = 1)
for i in b :
    if i !=45:
        print("sudoku is not valid ")
        break

else:
    print("for rows it is valid ")

    # 0 is for column's axis 
    # 1 is for row's axis

for rows it is valid 


In [6]:
c = np.sum(s,axis = 1)
for i in b :
    if i !=45:
        print("sudoku is not valid ")
        break

else:
    print("for colmns it is valid ")

    # 0 is for column's axis 
    # 1 is for row's axis

for colmns it is valid 


In [7]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [8]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [9]:
for i in range(0,9,3):
    for j in range(0,9,3):
        # print(s[i:i+3,j:j+3])
        n =s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [10]:
data = np.array([
    [18,85,78],  #student1
    [19,92,88],  #student2
    [17,76,95],  #student3
    [18,65,70],  #student4
    [20,90,85],  #student5
])

In [11]:
# get the shape of the matrix
data.shape


(5, 3)

In [12]:
# get the reshape of the matrix
data.reshape(3,5)

array([[18, 85, 78, 19, 92],
       [88, 17, 76, 95, 18],
       [65, 70, 20, 90, 85]])

In [13]:
# get the average age of all student 
# all the rows and first column
np.mean(data[:,0])

np.float64(18.4)

In [14]:
# extract math marks of all students 
data[:,1]

array([85, 92, 76, 65, 90])

In [15]:
# find the highest science mark 
np.max(data[:,2])

np.int64(95)

In [16]:
# get details of the student who scored more than 90 in maths
data[data[:,1]>90]

array([[19, 92, 88]])

In [17]:
# increase math marks of all students by 5 
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [18]:
# find how many students are youger than 19 
len(data[data[:,0]<19])

3