Numpy Indexing And Slicing Of Vector

In [21]:
import numpy as np

In [22]:
# start and end
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
arr[1:5]

array([12, 13, 14, 15])

In [24]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [25]:
arr[::-2]

array([20, 18, 16, 14, 12])

In [26]:
arr[3::2]

array([14, 16, 18, 20])

In [27]:
arr[4]

np.int64(15)

In [28]:
arr =np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Slicing 

In [29]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [30]:
arr[0,0]

np.int64(1)

In [31]:
# slicing
arr[1:5] 

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [32]:
arr[:5]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [33]:
# start,end,step
arr[0:6:2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [34]:
arr[1::3]

array([[ 6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25]])

In [35]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [36]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

BOOLEAN INDEXING

In [39]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [40]:
bool_index=arr % 2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
# only true elements 
arr =arr[bool_index] 
arr

array([12, 14, 16, 18, 20])